version: 2.1
parameters:
    app-name: tiles-map
orbs:
    deploy-to-heroku: betterdoc/deploy-to-heroku@4.1.0

defaults: &defaults
    working_directory: ~/demo-tiles
    docker:
        - image: circleci/node:lts
jobs:
    check_lint_and_test:
        <<: *defaults
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - run:
                  name: Install dependcies
                  command: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Check Linting
                  command: yarn lint
            - persist_to_workspace:
                  root: .
                  paths: .

workflows:
    version: 2.1
    deploy_new_version:
        jobs:
            - check_lint_and_test
            - deploy-to-heroku/docker-build-release:
                  app-name: tiles-map
                  requires:
                      - check_lint_and_test
                  filters:
                      branches:
                          only:
                              - setup/heroku
